export const infocaption = {
  introCaptionFirstLine: `Hi, I'm`,
  introCaptionSecondLine: 'Frontend Developer',
  introSubCaption: 'I code website and love to make it alive.',
  introBtnText: 'Contact me',
  aboutmeCaption: 'Passionate Frontend',
  fullName: 'Suppawit Satitsongtam',
  introSelf: `I'm Frontend Developer since 2018. I'm working with a high passion for making websites alive through animations. I always push myself to learn and explore new things and am really excited when doing some challenging tasks.`,
  aboutMeBtnText: 'View All',
  skillsTitle: 'Area of skills',
  skillsIntro:
    'These abilities track my job-specific duties and responsibilities. It comes from courses, vocational training, and job experiences. These also represent my working style and approach.',
  experienceTitle: 'Working experiences',
  contactMeTitle: `Let's get in touch`,
  contactMeCaption: 'Please do not hestigate to contact me via these if you interest my profile or want to send me any offers',
  phoneTitle: 'Call me',
  phoneText: '+66 89 6808 065',
  phoneNumber: '0896808065',
  githubTitle: 'Github',
  githubText: 'github.com/newtrn',
  githubLink: 'https://github.com/newtrn',
  emailTitle: 'Email',
  emailText: 't_ongyod@hotmail.com',
  codepenTitle: 'Codepen',
  codepneText: 'codepen.io/dodosike',
  codepenLink: 'https://codepen.io/dodosike',
}
